# 📝 Section 2: Homework 2: Comprehensive Data Cleaning and Analysis

### Assignment Overview

In this homework, you will clean, transform, and analyze the Titanic dataset. You will practice handling missing data, grouping and merging, creating pivot tables, and engineering new features. This assignment will test your ability to apply a variety of **Pandas** techniques to a real-world dataset.

In [10]:
# @title
from IPython.display import display, HTML

display(HTML("""
<div style="
    width: 100%;
    box-sizing: border-box;
    margin: 0 auto;
    padding: 6px;
    background: #2563EB;
    border-radius: 18px;
    font-family: Arial, sans-serif;
">

    <div style="
        width: 100%;
        box-sizing: border-box;
        background: #F8FAFC;
        border-radius: 14px;
        overflow: hidden;
    ">

        <!-- Header -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 32px 20px;
            text-align: center;
            background: #1E3A8A;
        ">

            <div style="
                color: #BFDBFE;
                font-size: 16px;
                font-weight: bold;
                letter-spacing: 1px;
                margin-bottom: 22px;
            ">
                PYTHON DATA ANALYSIS ASSIGNMENT
            </div>

            <div style="
                color: #FFFFFF;
                font-size: 42px;
                font-weight: bold;
                margin-bottom: 20px;
            ">
                Titanic Data Cleaning and Analysis
            </div>

            <div style="
                color: #DBEAFE;
                font-size: 20px;
            ">
                Data Cleaning, Grouping, Pivot Tables, Feature Engineering, and Outlier Handling
            </div>

        </div>

        <!-- Student Information -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 25px;
            background: #DBEAFE;
        ">

            <table style="
                width: 100%;
                border-collapse: separate;
                border-spacing: 0 7px;
                font-size: 16px;
            ">

                <tr>
                    <td style="
                        width: 32%;
                        padding: 13px 16px;
                        background: #1D4ED8;
                        color: white;
                        font-weight: bold;
                    ">
                        👤 Student Name
                    </td>

                    <td style="
                        width: 68%;
                        padding: 13px 16px;
                        background: #FFFFFF;
                        color: #1E3A8A;
                        font-weight: bold;
                    ">
                        Abdallah Saeed Fsafis
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #0891B2;
                        color: white;
                        font-weight: bold;
                    ">
                        🪪 Student ID
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #ECFEFF;
                        color: #164E63;
                        font-weight: bold;
                    ">
                        120211322
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #7C3AED;
                        color: white;
                        font-weight: bold;
                    ">
                        📘 Course Name
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #F5F3FF;
                        color: #4C1D95;
                        font-weight: bold;
                    ">
                        Field Training
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #059669;
                        color: white;
                        font-weight: bold;
                    ">
                        👨‍🏫 Instructor Name
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #ECFDF5;
                        color: #064E3B;
                        font-weight: bold;
                    ">
                        Anas Taha Mushtaha
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #EA580C;
                        color: white;
                        font-weight: bold;
                    ">
                        📝 Assignment Title
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #FFF7ED;
                        color: #7C2D12;
                        font-weight: bold;
                    ">
                        Data Cleaning and Analysis – Task 2
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #E11D48;
                        color: white;
                        font-weight: bold;
                    ">
                        📅 Submission Date
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #FFF1F2;
                        color: #881337;
                        font-weight: bold;
                    ">
                        July 9, 2026
                    </td>
                </tr>

            </table>

        </div>

        <!-- Overview -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 28px 40px;
            text-align: center;
            background: #CCFBF1;
        ">

            <div style="
                color: #0F766E;
                font-size: 21px;
                font-weight: bold;
                margin-bottom: 16px;
            ">
                📌 Notebook Overview
            </div>

            <div style="
                color: #134E4A;
                font-size: 16px;
                line-height: 1.8;
            ">
                This notebook uses the Titanic dataset to practice real-world data cleaning
                and data analysis skills using Python and Pandas.
                <br><br>
                The work includes loading the dataset, handling missing values, dropping
                unnecessary columns, standardizing text formats, grouping and merging data,
                creating pivot tables, engineering a TravelGroup feature, handling Fare
                outliers using the IQR method, and storing final summary statistics in a dictionary.
            </div>

        </div>

        <!-- Footer -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 18px;
            text-align: center;
            background: #0F172A;
            color: #CBD5E1;
            font-size: 14px;
        ">
            Developed using
            <span style="color:#67E8F9; font-weight:bold;">Python</span>,
            <span style="color:#93C5FD; font-weight:bold;">Pandas</span>,
            and
            <span style="color:#C4B5FD; font-weight:bold;">Google Colab</span>
        </div>

    </div>
</div>
"""))

---

## 🚢 1. Getting Started and Data Cleaning

### Instructions
1.  Import the **Pandas** library.
2.  Load the Titanic dataset from the specified URL.
3.  Perform the initial data cleaning:
    * Impute missing `Age` values with the **median**.
    * Fill missing `Embarked` values with the **mode** (the most frequent value).
    * Drop the `Cabin` column entirely.
4.  Display the first 10 rows of the cleaned DataFrame to verify your work.

In [11]:
# Import the Pandas library
import pandas as pd

# Load the Titanic dataset from the URL
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic_df = pd.read_csv(url)

# Replace missing Age values with the median Age
titanic_df["Age"] = titanic_df["Age"].fillna(titanic_df["Age"].median())

# Replace missing Embarked values with the mode
titanic_df["Embarked"] = titanic_df["Embarked"].fillna(titanic_df["Embarked"].mode()[0])

# Drop the Cabin column because it contains many missing values
titanic_df = titanic_df.drop(columns=["Cabin"])

# Standardize the Name column to title case
titanic_df["Name"] = titanic_df["Name"].str.title()

# Display the first 10 rows of the cleaned DataFrame
display(titanic_df.head(10))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q
6,7,0,1,"Mccarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C

---

## 📊 2. Grouping and Merging

### Instructions
1.  Group the cleaned DataFrame by `Pclass`.
2.  Calculate the **mean `Fare`** and the **count of passengers** for each class. *Hint: `.agg()` can be useful here.*
3.  Create a second, small DataFrame that maps `Pclass` values to a `ClassDescription` (e.g., 1 to "Upper", 2 to "Middle", 3 to "Lower").
4.  **Merge** your grouped data with this new DataFrame to add the descriptive class names.
5.  Display the final merged DataFrame.

In [12]:
# Group the cleaned DataFrame by passenger class
grouped_by_class = titanic_df.groupby("Pclass").agg({
    "Fare": "mean",
    "PassengerId": "count"
}).reset_index()

# Create a secondary DataFrame that describes each passenger class
class_desc_df = pd.DataFrame({
    "Pclass": [1, 2, 3],
    "ClassDescription": ["Upper", "Middle", "Lower"]
})

# Merge the grouped results with the class description DataFrame
merged_class_df = pd.merge(grouped_by_class, class_desc_df, on="Pclass")

# Display the merged DataFrame
display(merged_class_df)

   Pclass       Fare  PassengerId ClassDescription
0       1  84.154687          216            Upper
1       2  20.662183          184           Middle
2       3  13.675550          491            Lower

---

## 🔀 3. Creating a Pivot Table

### Instructions
1.  Create a **pivot table** from the cleaned `titanic_df`.
2.  The pivot table should show the **mean `Fare`**.
3.  Use `Embarked` for the **rows** (index) and `Sex` for the **columns**.
4.  Fill any missing values (`NaN`) in the resulting pivot table with `0`.
5.  Display the pivot table.

In [13]:
# Create a pivot table showing the mean Fare by Embarked and Sex
pivot_table = pd.pivot_table(
    titanic_df,
    values="Fare",
    index="Embarked",
    columns="Sex",
    aggfunc="mean"
)

# Fill missing values in the pivot table with 0
pivot_table = pivot_table.fillna(0)

# Display the pivot table
display(pivot_table)

Sex          female       male
Embarked
C         75.169805  48.262109
Q         12.634958  13.838922
S         39.143456  21.711996

---

## ✨ 4. Feature Engineering and Outlier Handling

### Instructions
1.  **Feature Engineering**: Create a new `TravelGroup` column in `titanic_df`. This column should categorize passengers based on their total family size (`SibSp` + `Parch` + 1).
    * **"Solo"**: Family size of 1.
    * **"Small"**: Family size of 2 or 3.
    * **"Large"**: Family size of 4 or more.
2.  **Outlier Handling**: Document your chosen method for handling outliers in the `Fare` column in the markdown cell below. Then, apply this method to your DataFrame.
3.  **Final Summary**:
    * Display the first 10 rows of the DataFrame with the new `TravelGroup` column and adjusted `Fare`.
    * Create a dictionary called `summary_stats` to store at least two summary statistics (e.g., mean `Fare` after outlier handling, number of "Solo" travelers).

### My Outlier Handling Method

I used the **IQR method** to handle outliers in the `Fare` column. First, I calculated Q1 and Q3, then calculated the IQR as `Q3 - Q1`. After that, I used the lower bound `Q1 - 1.5 * IQR` and the upper bound `Q3 + 1.5 * IQR`. Any Fare value outside this range was capped to the nearest boundary using `clip()`.

In [14]:
# 1. Feature Engineering: Create the TravelGroup column

# Calculate total travel group size for each passenger
titanic_df["TravelGroupSize"] = titanic_df["SibSp"] + titanic_df["Parch"] + 1

# Define a function to categorize passengers by travel group size
def categorize_travel_group(size):
    if size == 1:
        return "Solo"
    elif size <= 3:
        return "Small"
    else:
        return "Large"

# Apply the function to create the TravelGroup column
titanic_df["TravelGroup"] = titanic_df["TravelGroupSize"].apply(categorize_travel_group)


# 2. Outlier Handling: Apply the IQR method to the Fare column

# Calculate Q1, Q3, and IQR for Fare
Q1 = titanic_df["Fare"].quantile(0.25)
Q3 = titanic_df["Fare"].quantile(0.75)
IQR = Q3 - Q1

# Calculate the lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Cap Fare outliers to the nearest boundary
titanic_df["Fare"] = titanic_df["Fare"].clip(lower=lower_bound, upper=upper_bound)


# 3. Final Summary: Display the DataFrame and create the summary_stats dictionary

summary_stats = {
    "mean_fare_after_outlier_handling": titanic_df["Fare"].mean(),
    "max_travel_group_size": titanic_df["TravelGroupSize"].max(),
    "number_of_solo_travelers": (titanic_df["TravelGroup"] == "Solo").sum()
}

# Display the first 10 rows of the final DataFrame
display(titanic_df.head(10))

# Display the summary statistics dictionary
display(summary_stats)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,TravelGroupSize,TravelGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,2,Small
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,65.6344,C,2,Small
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1,Solo
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,2,Small
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1,Solo
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q,1,Solo
6,7,0,1,"Mccarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,1,Solo
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,5,Large
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,3,Small
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,2,Small

{'mean_fare_after_outlier_handling': np.float64(24.04681335578002),
 'max_travel_group_size': 11,
 'number_of_solo_travelers': np.int64(537)}

---

## ✅ Self-Assessment

Run the cell below to check your work. This script will evaluate the key components of your assignment and provide a score and feedback. **Make sure you have run all the cells above this one first.**

In [15]:
#@title Run this cell to check your work
import pandas as pd
from IPython.display import display, Markdown

def check_homework():
    """Checks the student's work and provides feedback."""
    score = 0
    total_points = 5
    feedback = []

    # Check 1: Data Cleaning
    try:
        if 'titanic_df' in globals() and isinstance(titanic_df, pd.DataFrame):
            cabin_dropped = 'Cabin' not in titanic_df.columns
            age_imputed = titanic_df['Age'].notna().all()
            embarked_filled = titanic_df['Embarked'].notna().all()
            if cabin_dropped and age_imputed and embarked_filled:
                score += 1
                feedback.append("- ✅ **Task 1 (Cleaning):** Passed. DataFrame is loaded and initial cleaning is correct.")
            else:
                error_msgs = []
                if not cabin_dropped: error_msgs.append("'Cabin' column not dropped")
                if not age_imputed: error_msgs.append("'Age' has missing values")
                if not embarked_filled: error_msgs.append("'Embarked' has missing values")
                feedback.append(f"- ❌ **Task 1 (Cleaning):** Incomplete. Issues found: {', '.join(error_msgs)}.")
        else:
            feedback.append("- ❌ **Task 1 (Cleaning):** Failed. DataFrame named `titanic_df` not found.")
    except Exception as e:
        feedback.append(f"- ❌ **Task 1 (Cleaning):** An error occurred: {e}")

    # Check 2: Grouping and Merging
    try:
        if 'merged_class_df' in globals() and isinstance(merged_class_df, pd.DataFrame):
            required_cols = ['Pclass', 'Fare', 'ClassDescription']
            # Accommodate different possible names for the count column
            count_col_present = any(col in merged_class_df.columns for col in ['PassengerId', 'Survived', 'Name'])
            if all(c in merged_class_df.columns for c in required_cols) and count_col_present:
                score += 1
                feedback.append("- ✅ **Task 2 (Grouping/Merging):** Passed. Grouping and merging were successful.")
            else:
                feedback.append("- ❌ **Task 2 (Grouping/Merging):** Failed. `merged_class_df` is missing required columns.")
        else:
            feedback.append("- ❌ **Task 2 (Grouping/Merging):** Failed. DataFrame `merged_class_df` not found.")
    except Exception as e:
        feedback.append(f"- ❌ **Task 2 (Grouping/Merging):** An error occurred: {e}")

    # Check 3: Pivot Table
    try:
        if 'pivot_table' in globals() and isinstance(pivot_table, pd.DataFrame):
            index_ok = pivot_table.index.name == 'Embarked'
            cols_ok = 'male' in pivot_table.columns and 'female' in pivot_table.columns
            nan_ok = not pivot_table.isna().any().any()
            if index_ok and cols_ok and nan_ok:
                score += 1
                feedback.append("- ✅ **Task 3 (Pivot Table):** Passed. Pivot table has the correct structure and no missing values.")
            else:
                feedback.append("- ❌ **Task 3 (Pivot Table):** Failed. Check index, columns, or missing value handling.")
        else:
            feedback.append("- ❌ **Task 3 (Pivot Table):** Failed. DataFrame `pivot_table` not found.")
    except Exception as e:
        feedback.append(f"- ❌ **Task 3 (Pivot Table):** An error occurred: {e}")

    # Check 4: Feature Engineering
    try:
        if 'titanic_df' in globals() and 'TravelGroup' in titanic_df.columns:
            expected_values = {"Solo", "Small", "Large"}
            actual_values = set(titanic_df['TravelGroup'].unique())
            if actual_values.issubset(expected_values):
                score += 1
                feedback.append("- ✅ **Task 4 (Feature Engineering):** Passed. `TravelGroup` column created correctly.")
            else:
                feedback.append("- ❌ **Task 4 (Feature Engineering):** Failed. `TravelGroup` contains unexpected values.")
        else:
            feedback.append("- ❌ **Task 4 (Feature Engineering):** Failed. `TravelGroup` column not found in `titanic_df`.")
    except Exception as e:
        feedback.append(f"- ❌ **Task 4 (Feature Engineering):** An error occurred: {e}")

    # Check 5: Summary Stats
    try:
        if 'summary_stats' in globals() and isinstance(summary_stats, dict):
            if len(summary_stats) >= 2:
                score += 1
                feedback.append("- ✅ **Task 5 (Summary Stats):** Passed. `summary_stats` dictionary is created with at least two entries.")
            else:
                feedback.append("- ❌ **Task 5 (Summary Stats):** Failed. Dictionary must contain at least two stats.")
        else:
            feedback.append("- ❌ **Task 5 (Summary Stats):** Failed. Dictionary `summary_stats` not found.")
    except Exception as e:
        feedback.append(f"- ❌ **Task 5 (Summary Stats):** An error occurred: {e}")

    # Final Feedback
    final_message = "**Homework Self-Assessment Feedback:**\n\n" + "\n".join(feedback)
    final_message += f"\n\n### **Final Score: {score}/{total_points}**"
    if score == total_points:
        final_message += "\n\nExcellent work! All checks passed."
    else:
        final_message += "\n\nSome tasks need revision. Please review the feedback above."

    display(Markdown(final_message))

check_homework()

**Homework Self-Assessment Feedback:**

- ✅ **Task 1 (Cleaning):** Passed. DataFrame is loaded and initial cleaning is correct.
- ✅ **Task 2 (Grouping/Merging):** Passed. Grouping and merging were successful.
- ✅ **Task 3 (Pivot Table):** Passed. Pivot table has the correct structure and no missing values.
- ✅ **Task 4 (Feature Engineering):** Passed. `TravelGroup` column created correctly.
- ✅ **Task 5 (Summary Stats):** Passed. `summary_stats` dictionary is created with at least two entries.

### **Final Score: 5/5**

Excellent work! All checks passed.