In [ ]:
# @title
from IPython.display import display, HTML

display(HTML("""
<div style="
    width: 100%;
    box-sizing: border-box;
    margin: 0 auto;
    padding: 6px;
    background: #2563EB;
    border-radius: 18px;
    font-family: Arial, sans-serif;
">

    <div style="
        width: 100%;
        box-sizing: border-box;
        background: #F8FAFC;
        border-radius: 14px;
        overflow: hidden;
    ">

        <!-- Header -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 32px 20px;
            text-align: center;
            background: #1E3A8A;
        ">

            <div style="
                color: #BFDBFE;
                font-size: 16px;
                font-weight: bold;
                letter-spacing: 1px;
                margin-bottom: 22px;
            ">
                PYTHON DATA ANALYSIS ASSIGNMENT
            </div>

            <div style="
                color: #FFFFFF;
                font-size: 42px;
                font-weight: bold;
                margin-bottom: 20px;
            ">
                Titanic Data Cleaning and Analysis
            </div>

            <div style="
                color: #DBEAFE;
                font-size: 20px;
            ">
                Data Cleaning, Grouping, Pivot Tables, Feature Engineering, and Outlier Handling
            </div>

        </div>

        <!-- Student Information -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 25px;
            background: #DBEAFE;
        ">

            <table style="
                width: 100%;
                border-collapse: separate;
                border-spacing: 0 7px;
                font-size: 16px;
            ">

                <tr>
                    <td style="
                        width: 32%;
                        padding: 13px 16px;
                        background: #1D4ED8;
                        color: white;
                        font-weight: bold;
                    ">
                        👤 Student Name
                    </td>

                    <td style="
                        width: 68%;
                        padding: 13px 16px;
                        background: #FFFFFF;
                        color: #1E3A8A;
                        font-weight: bold;
                    ">
                        Abdallah Saeed Fsafis
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #0891B2;
                        color: white;
                        font-weight: bold;
                    ">
                        🪪 Student ID
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #ECFEFF;
                        color: #164E63;
                        font-weight: bold;
                    ">
                        120211322
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #7C3AED;
                        color: white;
                        font-weight: bold;
                    ">
                        📘 Course Name
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #F5F3FF;
                        color: #4C1D95;
                        font-weight: bold;
                    ">
                        Field Training
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #059669;
                        color: white;
                        font-weight: bold;
                    ">
                        👨‍🏫 Instructor Name
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #ECFDF5;
                        color: #064E3B;
                        font-weight: bold;
                    ">
                        Anas Taha Mushtaha
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #EA580C;
                        color: white;
                        font-weight: bold;
                    ">
                        📝 Assignment Title
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #FFF7ED;
                        color: #7C2D12;
                        font-weight: bold;
                    ">
                        Data Cleaning and Analysis – Task 3
                    </td>
                </tr>

                <tr>
                    <td style="
                        padding: 13px 16px;
                        background: #E11D48;
                        color: white;
                        font-weight: bold;
                    ">
                        📅 Submission Date
                    </td>

                    <td style="
                        padding: 13px 16px;
                        background: #FFF1F2;
                        color: #881337;
                        font-weight: bold;
                    ">
                        July 9, 2026
                    </td>
                </tr>

            </table>

        </div>

        <!-- Overview -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 28px 40px;
            text-align: center;
            background: #CCFBF1;
        ">

            <div style="
                color: #0F766E;
                font-size: 21px;
                font-weight: bold;
                margin-bottom: 16px;
            ">
                📌 Notebook Overview
            </div>

            <div style="
                color: #134E4A;
                font-size: 16px;
                line-height: 1.8;
            ">
                This notebook uses the Titanic dataset to practice real-world data cleaning
                and data analysis skills using Python and Pandas.
                <br><br>
                The work includes loading the dataset, handling missing values, dropping
                unnecessary columns, standardizing text formats, grouping and merging data,
                creating pivot tables, engineering a TravelGroup feature, handling Fare
                outliers using the IQR method, and storing final summary statistics in a dictionary.
            </div>

        </div>

        <!-- Footer -->
        <div style="
            width: 100%;
            box-sizing: border-box;
            padding: 18px;
            text-align: center;
            background: #0F172A;
            color: #CBD5E1;
            font-size: 14px;
        ">
            Developed using
            <span style="color:#67E8F9; font-weight:bold;">Python</span>,
            <span style="color:#93C5FD; font-weight:bold;">Pandas</span>,
            and
            <span style="color:#C4B5FD; font-weight:bold;">Google Colab</span>
        </div>

    </div>
</div>
"""))

# Titanic Dataset Cleaning and Enhancement

This notebook cleans and enhances the Titanic dataset using Python and Pandas in Google Colab.  
The goal is to prepare the dataset for real-world data science, visualization, and AI modeling tasks.

In [ ]:
# Import the Pandas library for data handling and analysis
import pandas as pd

# Store the Titanic dataset URL in a variable
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

# Read the CSV file from the URL and store it in a DataFrame
titanic_df = pd.read_csv(url)

# Display the first 5 rows of the dataset to check that the data loaded correctly
display(titanic_df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Display the number of rows and columns in the dataset
print("Dataset shape:")
print(titanic_df.shape)

# Display the column names in the dataset
print("\nColumn names:")
print(titanic_df.columns)

# Display general information about the dataset
# This includes column names, data types, and non-missing values
print("\nDataset information:")
titanic_df.info()

# Display the number of missing values in each column
print("\nMissing values in each column:")
display(titanic_df.isnull().sum())

# Display the number of duplicated rows in the dataset
print("\nNumber of duplicated rows:")
print(titanic_df.duplicated().sum())

# Display basic summary statistics for numeric columns
print("\nSummary statistics:")
display(titanic_df.describe())

Dataset shape:
(891, 12)

Column names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Missing values in each column:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Number of duplicated rows:
0

Summary statistics:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# Store the number of rows before cleaning
rows_before_cleaning = titanic_df.shape[0]

# Store the number of duplicated rows before removing duplicates
duplicates_before = titanic_df.duplicated().sum()

# Store missing values before cleaning
missing_before = titanic_df.isnull().sum()

# Calculate the median value of the Age column
# The median is used because it is less affected by extreme values than the mean
age_median = titanic_df["Age"].median()

# Fill missing Age values with the median age
titanic_df["Age"] = titanic_df["Age"].fillna(age_median)

# Calculate the most frequent value in the Embarked column
# The mode is suitable for categorical columns
embarked_mode = titanic_df["Embarked"].mode()[0]

# Fill missing Embarked values with the most frequent value
titanic_df["Embarked"] = titanic_df["Embarked"].fillna(embarked_mode)

# Drop the Cabin column because it has many missing values
titanic_df = titanic_df.drop(columns=["Cabin"])

# Remove duplicated rows to ensure data integrity
titanic_df = titanic_df.drop_duplicates()

# Standardize passenger names using title case
titanic_df["Name"] = titanic_df["Name"].str.title()

# Standardize the Sex column by removing spaces and converting values to lowercase
titanic_df["Sex"] = titanic_df["Sex"].str.strip().str.lower()

# Standardize the Embarked column by removing spaces and converting values to uppercase
titanic_df["Embarked"] = titanic_df["Embarked"].str.strip().str.upper()

# Store the number of rows after cleaning
rows_after_cleaning = titanic_df.shape[0]

# Store missing values after cleaning
missing_after = titanic_df.isnull().sum()

# Display cleaning results
print("Rows before cleaning:", rows_before_cleaning)
print("Rows after cleaning:", rows_after_cleaning)
print("Duplicated rows before cleaning:", duplicates_before)
print("Median Age used for imputation:", age_median)
print("Mode Embarked used for imputation:", embarked_mode)

print("\nMissing values before cleaning:")
display(missing_before)

print("\nMissing values after cleaning:")
display(missing_after)

# Display the cleaned dataset
display(titanic_df.head())

Rows before cleaning: 891
Rows after cleaning: 891
Duplicated rows before cleaning: 0
Median Age used for imputation: 28.0
Mode Embarked used for imputation: S

Missing values before cleaning:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Missing values after cleaning:

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [ ]:
# Create a new column called FamilySize
# It represents the total number of people traveling together
# SibSp = siblings/spouses, Parch = parents/children, +1 = the passenger himself/herself
titanic_df["FamilySize"] = titanic_df["SibSp"] + titanic_df["Parch"] + 1

# Define a function to classify passengers based on their family/travel group size
def classify_travel_group(size):
    # If the passenger is alone, classify as Solo
    if size == 1:
        return "Solo"

    # If the group size is 2 or 3, classify as Small
    elif size <= 3:
        return "Small"

    # If the group size is 4 or more, classify as Large
    else:
        return "Large"

# Apply the function to create a new TravelGroup column
titanic_df["TravelGroup"] = titanic_df["FamilySize"].apply(classify_travel_group)

# Create AgeGroup to make the Age column easier to analyze
# This groups passengers into age categories
titanic_df["AgeGroup"] = pd.cut(
    titanic_df["Age"],
    bins=[0, 12, 19, 59, 100],
    labels=["Child", "Teen", "Adult", "Senior"]
)

# Display selected columns to check the new engineered features
display(titanic_df[["Age", "AgeGroup", "SibSp", "Parch", "FamilySize", "TravelGroup"]].head(10))

    Age AgeGroup  SibSp  Parch  FamilySize TravelGroup
0  22.0    Adult      1      0           2       Small
1  38.0    Adult      1      0           2       Small
2  26.0    Adult      0      0           1        Solo
3  35.0    Adult      1      0           2       Small
4  35.0    Adult      0      0           1        Solo
5  28.0    Adult      0      0           1        Solo
6  54.0    Adult      0      0           1        Solo
7   2.0    Child      3      1           5       Large
8  27.0    Adult      0      2           3       Small
9  14.0     Teen      1      0           2       Small

In [ ]:
# Store the original Fare values before handling outliers
# This helps us compare the Fare column before and after outlier treatment
titanic_df["OriginalFare"] = titanic_df["Fare"]

# Calculate the first quartile Q1 for the Fare column
# Q1 represents the value below which 25% of the Fare values fall
Q1 = titanic_df["Fare"].quantile(0.25)

# Calculate the third quartile Q3 for the Fare column
# Q3 represents the value below which 75% of the Fare values fall
Q3 = titanic_df["Fare"].quantile(0.75)

# Calculate the Interquartile Range
# IQR measures the spread of the middle 50% of the Fare values
IQR = Q3 - Q1

# Calculate the lower bound for acceptable Fare values
lower_bound = Q1 - 1.5 * IQR

# Calculate the upper bound for acceptable Fare values
upper_bound = Q3 + 1.5 * IQR

# Count how many Fare values are considered outliers before handling them
fare_outliers_before = titanic_df[
    (titanic_df["Fare"] < lower_bound) | (titanic_df["Fare"] > upper_bound)
].shape[0]

# Cap Fare values using the lower and upper bounds
# Values below the lower bound become equal to the lower bound
# Values above the upper bound become equal to the upper bound
titanic_df["Fare_Capped"] = titanic_df["Fare"].clip(
    lower=lower_bound,
    upper=upper_bound
)

# Count how many Fare values are still outside the bounds after capping
fare_outliers_after = titanic_df[
    (titanic_df["Fare_Capped"] < lower_bound) | (titanic_df["Fare_Capped"] > upper_bound)
].shape[0]

# Display the IQR values and outlier handling results
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Fare outliers before handling:", fare_outliers_before)
print("Fare outliers after handling:", fare_outliers_after)

# Display selected columns to compare original Fare and capped Fare
display(titanic_df[["OriginalFare", "Fare_Capped"]].head(10))

Q1: 7.9104
Q3: 31.0
IQR: 23.0896
Lower bound: -26.724
Upper bound: 65.6344
Fare outliers before handling: 116
Fare outliers after handling: 0

   OriginalFare  Fare_Capped
0        7.2500       7.2500
1       71.2833      65.6344
2        7.9250       7.9250
3       53.1000      53.1000
4        8.0500       8.0500
5        8.4583       8.4583
6       51.8625      51.8625
7       21.0750      21.0750
8       11.1333      11.1333
9       30.0708      30.0708

## Cleaning and Enhancement Documentation

In this step, the Titanic dataset was cleaned and enhanced to make it more reliable for data analysis and AI modeling.

The cleaning process included handling missing values, removing duplicates, standardizing text formats, creating new useful features, and handling Fare outliers.

Missing Age values were filled using the median age because the median is less affected by extreme values.

Missing Embarked values were filled using the mode because Embarked is a categorical column.

The Cabin column was dropped because it had too many missing values.

Duplicate rows were checked and removed to ensure data integrity.

Passenger names were standardized using title case, Sex values were converted to lowercase, and Embarked values were converted to uppercase.

New features were created:
- FamilySize: calculated using SibSp + Parch + 1
- TravelGroup: classifies passengers as Solo, Small, or Large
- AgeGroup: classifies passengers as Child, Teen, Adult, or Senior

Fare outliers were handled using the IQR method. The lower bound was calculated as Q1 - 1.5 * IQR, and the upper bound was calculated as Q3 + 1.5 * IQR. Values outside these bounds were capped to the nearest acceptable boundary.

In [ ]:
# Create a final summary dictionary to document the cleaning results
cleaning_summary = {
    # Number of rows before cleaning
    "Rows before cleaning": rows_before_cleaning,

    # Number of rows after cleaning
    "Rows after cleaning": rows_after_cleaning,

    # Number of duplicated rows found before cleaning
    "Duplicated rows before cleaning": duplicates_before,

    # Median value used to fill missing Age values
    "Median Age used": age_median,

    # Mode value used to fill missing Embarked values
    "Mode Embarked used": embarked_mode,

    # Number of Fare outliers before applying IQR capping
    "Fare outliers before handling": fare_outliers_before,

    # Number of Fare outliers after applying IQR capping
    "Fare outliers after handling": fare_outliers_after,

    # Mean Fare after capping outliers
    "Mean capped Fare": titanic_df["Fare_Capped"].mean(),

    # Maximum family/travel group size
    "Maximum Family Size": titanic_df["FamilySize"].max()
}

# Display the final cleaned and enhanced dataset
print("Final cleaned and enhanced Titanic dataset:")
display(titanic_df.head(10))

# Display the final cleaning summary
print("Final cleaning summary:")
display(cleaning_summary)

# Display the number of passengers in each TravelGroup category
print("Passenger count by TravelGroup:")
display(titanic_df["TravelGroup"].value_counts())

# Display the number of passengers in each AgeGroup category
print("Passenger count by AgeGroup:")
display(titanic_df["AgeGroup"].value_counts())

Final cleaned and enhanced Titanic dataset:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,TravelGroup,AgeGroup,OriginalFare,Fare_Capped
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,2,Small,Adult,7.2500,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,2,Small,Adult,71.2833,65.6344
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1,Solo,Adult,7.9250,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,2,Small,Adult,53.1000,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1,Solo,Adult,8.0500,8.0500
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q,1,Solo,Adult,8.4583,8.4583
6,7,0,1,"Mccarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,1,Solo,Adult,51.8625,51.8625
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,5,Large,Child,21.0750,21.0750
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,3,Small,Adult,11.1333,11.1333
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,2,Small,Teen,30.0708,30.0708

Final cleaning summary:

{'Rows before cleaning': 891,
 'Rows after cleaning': 891,
 'Duplicated rows before cleaning': np.int64(0),
 'Median Age used': 28.0,
 'Mode Embarked used': 'S',
 'Fare outliers before handling': 116,
 'Fare outliers after handling': 0,
 'Mean capped Fare': np.float64(24.04681335578002),
 'Maximum Family Size': 11}

Passenger count by TravelGroup:

TravelGroup
Solo     537
Small    263
Large     91
Name: count, dtype: int64

Passenger count by AgeGroup:

AgeGroup
Adult     701
Teen       95
Child      69
Senior     26
Name: count, dtype: int64

In [ ]:
# Create a cleaner final summary dictionary using regular Python data types
# This makes the output easier to read and present

final_summary = {
    "Rows before cleaning": int(rows_before_cleaning),
    "Rows after cleaning": int(rows_after_cleaning),
    "Duplicated rows before cleaning": int(duplicates_before),
    "Median Age used": float(age_median),
    "Mode Embarked used": str(embarked_mode),
    "Fare outliers before handling": int(fare_outliers_before),
    "Fare outliers after handling": int(fare_outliers_after),
    "Mean capped Fare": round(float(titanic_df["Fare_Capped"].mean()), 2),
    "Maximum Family Size": int(titanic_df["FamilySize"].max())
}

# Display the clean final summary
display(final_summary)

{'Rows before cleaning': 891,
 'Rows after cleaning': 891,
 'Duplicated rows before cleaning': 0,
 'Median Age used': 28.0,
 'Mode Embarked used': 'S',
 'Fare outliers before handling': 116,
 'Fare outliers after handling': 0,
 'Mean capped Fare': 24.05,
 'Maximum Family Size': 11}

## Conclusion

The Titanic dataset was successfully cleaned and enhanced using Pandas. Missing values were handled, duplicate rows were checked, text formats were standardized, new features were created, and Fare outliers were managed using the IQR method.

The final dataset is now more reliable and ready for data visualization, reporting, or AI modeling tasks.